language: ruby
rvm:
  - 2.0.0
before_script:
  - cp config/secrets.yml.example config/secrets.yml
  - cp php/website/config.php.incvs php/website/config.php
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:setup
